### ISSUE TITLE
Provide direct APKs?

### ISSUE THREAD

**Issue by araspik** [CorvetteCole/PixelWatchFace#10]
Could you please build and provide the direct APK files along with the Play Store links? Trying to avoid Google, but it's hard.

**Comment by CorvetteCole** [comment]
I would love to, unfortunately this app makes use of some Google Wearables
APIs for transferring data between the phone and watch face so I don't know
how it would work on a degoogled device. I can get some APKs for you
regardless

**Comment by araspik** [comment]
Thanks! I'm going to try to remove my account after sideloading the APKs, and hopefully that lets me use it without Google. I didn't have the associated app installed on my phone and it worked just fine, so hopefully it shouldn't be an issue.

**Comment by CorvetteCole** [comment]
It should work fine but weather may never work and some functionality will be unsupported

**Comment by CorvetteCole** [comment]
@araspik I have started publishing APKs upon major releases (milestone completions). You can find them in the "releases" category
