### ISSUE TITLE
Moto 360/screen with chin battery percentage placement off screen

### ISSUE THREAD

**Issue by CoolGames** [CorvetteCole/PixelWatchFace#11]
Cole,
I use the Wear OS on Google Pixel 3a
I can add watch faces on Moto 360 Sport.
I can access Play Store from watch.
Settings says Pixel Watch Face is installed but I am not seeing it.

```
$ adb -s 127.0.0.1:4444 shell pm -l | grep pixel
package:com.corvettecole.pixelwatchface
$ adb -s 127.0.0.1:4444 shell pm path com.corvettecole.pixelwatchface
package:/data/app/com.corvettecole.pixelwatchface-1/base.apk
package:/data/app/com.corvettecole.pixelwatchface-1/split_config.en.apk
package:/data/app/com.corvettecole.pixelwatchface-1/split_config.mdpi.apk

```

I am able to do developer ADB access and Bugreports

 ```
Package [com.corvettecole.pixelwatchface] (1817149):
 userId=10038
 pkg=Package{c17aa4e com.corvettecole.pixelwatchface}
 codePath=/data/app/com.corvettecole.pixelwatchface-1
 resourcePath=/data/app/com.corvettecole.pixelwatchface-1
 legacyNativeLibraryDir=/data/app/com.corvettecole.pixelwatchface-1/lib

```

Feature request second hand not seconds digital text.
![WatchFace](https://user-images.githubusercontent.com/149711/71377840-d14b1380-2593-11ea-8a83-318507fa808e.png)

Here is screencap but disappears from choices on phone and requires making choice on watch settings.
![ChooseFace](https://user-images.githubusercontent.com/149711/71378217-11f75c80-2595-11ea-8976-eb7c90b18c11.png)
Wrong Preview.

![screenv2](https://user-images.githubusercontent.com/149711/71377668-72859a00-2593-11ea-8df0-af43e6a81857.png)
Battery Level too low on round screen with square image.

UPDATE:
Found the face on Pixel 3a in Wear OS choices under "P".

![Screenshot_20191223-142805](https://user-images.githubusercontent.com/149711/71377055-9b0c9480-2591-11ea-863f-45f454b33cca.png)

**Comment by CorvetteCole** [comment]
I've been very busy lately but I will attempt to fix the battery percentage soon using some voodoo math I've come up with

**Comment by CorvetteCole** [comment]
#19 will fix this issue when it is implemented. Until then, I will leave this open

**Comment by CorvetteCole** [comment]
fixed in latest release
