### ISSUE TITLE
Feature request: make the WearOS logo an option

### ISSUE THREAD

**Issue by motorro** [CorvetteCole/PixelWatchFace#16]
Hi! Thanks for the great watch-face!
Could you please consider displaying WearOS logo an option?
Having only the data widgets looks better for me :)
The more advanced feature would be a toggle + custom logo upload of cause ;)

**Comment by CorvetteCole** [comment]
WearOS logo will become an optional feature with default off in the next update (I like that more too). Thanks for the feedback!

**Comment by CorvetteCole** [comment]
This has been added to the GitHub in a recent commit, it should be available in the Play Store once 1.4.1 is complete
