### ISSUE TITLE
Dark Sky API possible shutdown

### ISSUE THREAD

**Issue by davwheat** [CorvetteCole/PixelWatchFace#32]
https://blog.darksky.net/dark-sky-has-a-new-home/

Since Apple are now taking over Dark Sky, they may close their API at the end of 2021.

**Comment by CorvetteCole** [comment]
Well this sucks. I am running in to limitations with OpenWeatherMap's free API now as well, due to the number of users some weather updates are unreliable. My only option right about now is to start charging people a subscription price for weather access. It would only be like $3/yr but I am worried about being crucified by angry users :/. Thinking about building my own weather api....

**Comment by CorvetteCole** [comment]
@davwheat would you think users would be willing to pay for the weather? I'm looking for input on this, I cannot afford to provide it at no charge and I am hitting free API limitations causing unreliable weather updates at the moment

**Comment by davwheat** [comment]
I honestly  wouldn't. If I need to know the weather, I'd use my Alexa or Nest Mini, or just ask the Assistant on the watch, or open the weather app.

I'm sure some people would, but not that many.

Some alternatives (definitely not as good as Dark Sky) could be...

- https://weatherapi.com
- https://weatherstack.com

These both have free tiers, and we could enter our own API keys like we did with Dark Sky.

---

WeatherStack **does** passing a lat/lon, as does Weather API.

```
http://api.weatherstack.com/current
    ? access_key = YOUR_ACCESS_KEY
    & query = 40.7831,-73.9712
```

PS: the reason I wouldn't pay is because I'm a student. Prioritisation!

**Comment by nyoma-diamond** [comment]
This might be slightly unrelated, but I've noticed that even with an existing Dark Sky API key I am unable to get weather data. OpenWeatherMap also doesn't work.

**Comment by davwheat** [comment]
I've had issues like that but I don't know why. It could be WearOS trying to optimise battery?

It's never lasted that long, and usually starts working after a few days.

**Comment by CorvetteCole** [comment]
@napostrophe make sure your Dark Sky API key is correct. My other suggestion would be clear the watch face app data or reinstall. I have a new "wizard" that makes sure everything is set up properly for weather updates. Still need to figure out what to do with these weather thing...

**Comment by mucke5** [comment]
Each user could create their own free API key from Weatherbit and enter it into the app?
![https___www weatherbit io_account_dashboard](https://user-images.githubusercontent.com/13103826/80791724-cd0eb280-8b92-11ea-9aca-6fa354309a27.png)

**Comment by CorvetteCole** [comment]
I have a rough plan now if anyone wants to give feedback on it.

Stage 1:
By May 20th, release an update that does the following:
1. Disables weather by default (including on current installs)
2. Shows a pop up on the watch after update which prompts the user to open the phone app to re-enable weather
3. In the phone app, include a brief explanation of why weather was disabled (unreliable and no money for proper API)
4. Allow users to re-enable weather in the phone app with a new one time in-app purchase of like $1.50 USD. Except now, the API will be getting forecasts from https://www.met.no/ and showing the latest one. This is not technically current weather but should be close enough temporarily

Stage 2:
1. Using the money from in-app purchases, I can spend a large amount of time building my own weather API that gathers data from all sorts of places to provide accurate current weather data. I will also be implementing a lot of Dark Sky's things like those super accurate 1 hour forecasts over time.
2. Release a bespoke weather app as well built upon this new weather API to take over Dark Sky's throne. 

I'm in kind of a tough spot here, and I want to make sure that I don't drive users away by locking weather behind a $1.50 purchase. Is that reasonable? All costs will go towards development of a new current weather API to replace the temporary solution I will be using, and this and future projects will remain firmly open source.

Thanks

**Comment by davwheat** [comment]
Could you please keep an option to use the Dark Sky API from now on? Even just a hidden option that needs you to tap somewhere 10 times to enable? I don't see any reason to disable functionality that still works for another year and a half.

**Comment by CorvetteCole** [comment]
@davwheat I guess my reply never got posted, I swear I wrote it and commented.... Anyways, yes I will keep the Dark Sky API for now. Good suggestion. If you have a Dark Sky API key saved when I release this next update, you will have access to the Dark Sky and weather settings, otherwise they will be grayed out for users until they complete the in-app purchase. At some point the Dark Sky API will be removed as an option, likely when I restructure the phone app and watch weather handling awhile after this temporary fix happens

**Comment by CorvetteCole** [comment]
You can track the status of this issue fix at https://github.com/CorvetteCole/PixelWatchFace/milestone/4

I will be closing this issue for now
