### ISSUE TITLE
Weather options do not work until specific option is checked.

### ISSUE THREAD

**Issue by eshrh** [CorvetteCole/PixelWatchFace#4]
Hello! I really liked this watch face, but I found this bug while I was trying it out.

The weather option does not show at first if you just toggle the "Show the temperature" option, or any of the other temperature options, since the watchface doesn't have location permissions yet. It only requests this once you check the "Show the current weather as an icon" option.

It'd probably make more sense to request this permission as soon as the watchface is installed.

**Watch:**
- TicWatch Pro
- WearOS 2.6

**Phone:**
- Pixel 3
- Android 9

**Comment by CorvetteCole** [comment]
I figured it shouldn't have location access unless you were doing something that required it (weather). But irregardless, this is a good bug report and I will fix this.

**Comment by CorvetteCole** [comment]
This bug has been fixed in the current GitHub version. Will be released to the Play Store soon.
