### ISSUE TITLE
New onboarding messages don't scale correctly

### ISSUE THREAD

**Issue by davwheat** [CorvetteCole/PixelWatchFace#45]
![IMG_20200606_115029](https://user-images.githubusercontent.com/7406822/83942531-0ff42380-a7ec-11ea-9c79-b1262ce6f745.jpg)

**Comment by CorvetteCole** [comment]
thanks for the bug report, this is why I'm running it through beta before full release. I'll fix this by autoscaling text, thanks for the bug report!

**Comment by CorvetteCole** [comment]
@davwheat what watch is that? For testing purposes

**Comment by davwheat** [comment]
It's the Fossil Sport (4th Gen)

**Comment by CorvetteCole** [comment]
thanks!

**Comment by CorvetteCole** [comment]
@davwheat did any of the other onboarding dialogs present similar behavior or just this one? I just fixed this layout but may change the others if there are problems with them

**Comment by davwheat** [comment]
It was the same case with the others too.

**Comment by CorvetteCole** [comment]
got it, thanks again. Will fix all of these. Would you like to be made an internal tester of the app? Updates made to internal testing are much more likely to be broken but they are a lot faster for testing purposes. If no, I understand. If so shoot an email to support@corvettecole.com with your google account email and I'll add you to the internal testing group

**Comment by davwheat** [comment]
Pinged off an email! :)

**Comment by CorvetteCole** [comment]
I have pushed an update fixing this to the internal testing branch. You should see an update on your watch available immediately. To trigger the onboarding dialogs, reset the app data of the watch face (your settings will all be resynced when you trigger a change in the phone app). I will re-open this if you find it to still be an issue, thanks!

**Comment by davwheat** [comment]
Perfect!

**Comment by davwheat** [comment]
@CorvetteCole I did just notice that after the data clear, weather has disappeared. My data is still in the phone app, but I can't actually see it on the watch.

**Comment by CorvetteCole** [comment]
can you try changing a setting in the phone to re-sync your settings?

**Comment by davwheat** [comment]
I've tried that already (as the WearOS logo wasn't showing either). My other settings (such as European date format) applied fine after clearing the watch app data.

**Comment by CorvetteCole** [comment]
So this new version also automagically sets some settings by default (24 hour time, European date format, Celsius temperature) based on your region and device settings. Is it not responding to any settings changes?

**Comment by davwheat** [comment]
It responds to my changes, but I cannot toggle weather on and off to "resync" it as it was disabled.

**Comment by CorvetteCole** [comment]
is the unlock now button present for the in-app purchase?

**Comment by davwheat** [comment]
Yes, but my dark sky settings are still present.

**Comment by CorvetteCole** [comment]
what happens when you click it again? This purchase is non-consumable so it
is impossible to be charged twice, don't worry.

**Comment by CorvetteCole** [comment]
I think this might be related to becoming an internal tester. you should
see test cards you can use, use the one that approves instantly. This may
not be a bug at all

**Comment by davwheat** [comment]
Ah, I thought it was going to remain free for existing weather users

>  If you have a Dark Sky API key saved when I release this next update, you will have access to the Dark Sky and weather settings

https://github.com/CorvetteCole/PixelWatchFace/issues/32#issuecomment-623020971

**Comment by davwheat** [comment]
No test cards appear -- I think those are only for you as you're the app developer.

**Comment by CorvetteCole** [comment]
oh you haven't purchased the weather unlock. I see. It would be quite
involved to restrict my weather providers to ONLY use Dark Sky. The way
I've built the system is so that with Dark Sky in use the other 5 weather
providers are also available as fallbacks in case Dark Sky fails for
whatever reason. Massive redundancy so we never have API issues again

**Comment by CorvetteCole** [comment]
Do you need a code to unlock the weather? I understand not everybody can purchase it

**Comment by davwheat** [comment]
No, don't worry. It's not a priority as I can still use the weather tile on WearOS. It's just a thing that's nice to have. Thanks for offering, though.
