### ISSUE TITLE
Broken WearOS Icon

### ISSUE THREAD

**Issue by Daninator1** [CorvetteCole/PixelWatchFace#49]
App Version: 1.5.5

After updating to the new version, the wear os icon looks broken, maybe some kind of anti aliasing problem? Also affects ambient mode.

![screenshot](https://user-images.githubusercontent.com/2072948/84268632-40a7c600-ab28-11ea-8817-85e8038f4bbe.png)

**Comment by davwheat** [comment]
Can't reproduce on internal testing branch.

**Comment by CorvetteCole** [comment]
@Daninator1 What watch do you have? For some reason I am only getting reports from those with a Ticwatch C2. This appears to be a canvas scaling bug with the new hardware acceleration I introduced in this update, I'm looking in to a fix

**Comment by Daninator1** [comment]
I own a Ticwatch E2 so this may be the reason.
I can also test builds on my watch if needed for a fix.

**Comment by jpwinnerjr** [comment]
Icon issue is also present on TicWatch Pro 4G/LTE

**Comment by CorvetteCole** [comment]
This issue appears to only present itself on TicWatch devices so far... I
may disable hardware acceleration on those devices. Or maybe globally, it
doesn't have a huge performance impact. Working on a fix....

**Comment by CorvetteCole** [comment]
@Daninator1 is this issue still present in the current beta? Thanks

**Comment by Daninator1** [comment]
Just joined the beta as I didn't know there was one available but haven't received a new build yet. Problem on Google's side or didn't the beta deployment work correctly?

**Comment by davwheat** [comment]
After joining, it should appear as an app update on your phone and/or
watch. :)

**Comment by Daninator1** [comment]
Yeah I know, however after a couple of hours there's still no new version available. Do you have the version number of the beta so I can recheck?

**Comment by davwheat** [comment]
On my watch, the version is `1.5.5.2`, and on my phone it's `1.5.5.1` (strangely).

I'm also an internal tester, not a beta tester so it might be a version behind or something.

**Comment by Daninator1** [comment]
Thanks, I got `1.5.5.1` on both of them so the beta version on Google Play hasn't been deployed yet it seems 🤔

**Comment by CorvetteCole** [comment]
@davwheat the phone is still on 1.5.5.1 because there is no update for it. I can update the apps individually which can lead to somewhat confusing versioning. I try to keep them roughly the same

**Comment by Daninator1** [comment]
Okay I got it, as the update only concerned the wear app it also only showed up on the Play Store on my watch, not my phone. Regarding the bug, it's fixed now!

**Comment by CorvetteCole** [comment]
Hardware acceleration disabled for now to resolve this bug
