### ISSUE TITLE
Improve your watch face performance with hardware acceleration

### ISSUE THREAD

**Issue by mucke5** [CorvetteCole/PixelWatchFace#54]
Is this perhaps interesting or not necessary?
https://developer.android.com/training/wearables/watch-faces/hardware-acceleration

**Comment by CorvetteCole** [comment]
Hardware acceleration was introduced in the 1.5.5 update but I have turned it back off in the 1.5.5.2 update due to bitmap rendering issues on Ticwatch devices. I am looking in to ways to work around this, but the performance change is fairly minimal with my watch face
