### ISSUE TITLE
Date & weather text difficult to read in ambient mode

### ISSUE THREAD

**Issue by davwheat** [CorvetteCole/PixelWatchFace#7]
The date and weather text is shown with an outline in ambient mode to prevent/reduce burn-in.

The only issue is that this makes the text much more difficult to read.

Maybe a possible solution to this could either be to increase the font size slightly or replace the outlined text with dark grey solid text in ambient mode.

**Comment by CorvetteCole** [comment]
hey can you join the beta program and let me know what you think? I've
replaced the outline for date & weather in the beta

**Comment by davwheat** [comment]
Sure! Just joined -- I'll report back soon.

**Comment by davwheat** [comment]
It definitely looks a lot better. One thing I've just realised: won't the small circle showing you have notifications overlap the battery percentage text?

**Comment by CorvetteCole** [comment]
yes that's a known bug I'm just so busy lately I haven't been able to work on the app much
